version: '3'
services:
  # 백엔드
  django:
    build:
      context: .
      dockerfile: ./Dockerfile/django.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    command: ./scripts/start_django.sh
  # 데이터베이스
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  db-data:
networks:
  backend:
